# Generated by Django 4.0.5 on 2022-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.BigIntegerField(null=True),
        ),
    ]
