# Generated by Django 4.0.6 on 2022-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_site', '0002_player_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='surname',
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='foot',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.BigIntegerField(null=True),
        ),
    ]
