# Generated by Django 4.0.6 on 2022-08-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm_site', '0004_clubs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
    ]
